# Generated by Django 5.2.14 on 2026-05-28 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=10)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('original_unit', models.CharField(blank=True, default='', max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('flag_severity', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='', max_length=10)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.ingestionjob')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('unflagged', 'Unflagged'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('comment', 'Comment'), ('edited', 'Edited')], max_length=20)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='review.normalizedrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='core.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
